project:
  type: website
  output-dir: docs

website:
  title: "Andrew Bartnik"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Portfolio.qmd
      - proj_pubs.qmd
      - resume.pdf
      - about.qmd
      


format:
  html:
    theme: 
      light: cerulean
      dark: slate
    css: styles.css
    toc: true

editor: visual

