project:
  type: website
  output-dir: docs

website:
  title: "Andrew Bartnik"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - Portfolio.qmd
      - proj_pubs.qmd
      - href: CV/resume.pdf
        text: CV
      - posts.qmd
      - about.qmd
      
      


format:
  html:
    theme: 
      - styles.scss
    mainfont: Nunito
    toc: true

editor: visual

