project:
  type: website
  output-dir: docs

website:
  title: "Andrew Bartnik"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - Portfolio.qmd
      - href: CV/resume.pdf
        text: CV
      - about.qmd
  page-footer: 
    background: "#4682B4"
    left: "Andrew Bartnik"
    right: 
      - icon: github
        href: https://github.com/andrewbartnik
      - icon: twitter
        href: https://twitter.com/andrew_bartnik      
      


format:
  html:
    theme: 
      - styles.scss
    mainfont: Nunito
    toc: true

editor: visual

