project:
  type: website
  output-dir: docs

website:
  favicon: photos/planet.png
  navbar:
    logo: photos/planet.png
    right:
      - href: index.qmd
        text: Home
      - Portfolio.qmd
      - href: CV/resume.pdf
        text: CV
      - about.qmd
      - icon: github
        href: https://github.com/andrewbartnik/
      - icon: twitter
        href: https://twitter.com/andrew_bartnik
      - icon: linkedin
        href: https://www.linkedin.com/in/andrewbartnik/
      - icon: envelope
        href: mailto:andrewbartnik@bren.ucsb.edu
  page-footer: 
    background: "#4682B4"
    right: 
      - icon: github
        href: https://github.com/andrewbartnik
      - icon: twitter
        href: https://twitter.com/andrew_bartnik      
    left: This website was build using [Quarto](https://quarto.org/)


format:
  html:
    theme: 
      - styles.scss
    mainfont: Nunito
    toc: true

editor: visual

